# -*- coding: utf-8 -*-

QUIT = 'QUIT'
SAVE = 'SAVE'

UI_RESIZE = 'UI_RESIZE'

NEXT = 'NEXT'
PREV = 'PREV'
INCREASE_DELAY = 'INCREASE_DELAY'
REDUCE_DELAY = 'REDUCE_DELAY'

NEXT_SCREEN = 'NEXT_SCREEN'
PREV_SCREEN = 'PREV_SCREEN'
TOGGLE_SCREEN = 'TOGGLE_SCREEN'
CYCLE_SCREENS = 'CYCLE_SCREENS'

NEXT_ON_SCREEN = 'NEXT_ON_SCREEN'
PREV_ON_SCREEN = 'PREV_ON_SCREEN'

INCREMENT_RATING = 'INCREMENT_RATING'
DECREMENT_RATING = 'DECREMENT_RATING'
INCREMENT_PURITY = 'INCREMENT_PURITY'
DECREMENT_PURITY = 'DECREMENT_PURITY'
TOGGLE_TAG = 'TOGGLE_TAG'
